project:
  type: book
  output-dir: docs

book:
  title: "Kenai Watershed Forum Water Temperature Loggers [DRAFT]"
  author: "Benjamin Meyer, Kenai Watershed Forum"
  date: "`r Sys.Date`"
  page-navigation: true
  chapters:
    - index.qmd
    - methods.qmd
    - summary.qmd
    - references.qmd

  repo-url: https://github.com/Kenai-Watershed-Forum/kwf_temp_loggers
  repo-actions: [edit]
  search:
    location: sidebar
    type: textbox
  downloads: [docx]

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of contents
    number-sections: true
    highlight-style: github

editor: visual

prefer-html: true

